### ISSUE TITLE
Not Working with Open Jdk 11

### ISSUE THREAD

**Issue by lbernollin** [ebean-orm-tools/ebean-eclipse-enhancer#10]
When i enable the Ebean Enhancer 11.x plugin i got 
`java.lang.IllegalArgumentException: Unsupported class file major version 55`

With a spring boot project using open jdk 11

Full error log :
`eclipse.buildId=4.9.0.I20180906-0745
java.version=11.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data file:/home/toto/workspace/ -os linux -ws gtk -arch x86_64

io.ebean.eclipse.enhancer
Error
Wed Dec 12 17:01:01 CET 2018
Error during enhancement java.lang.IllegalArgumentException: Unsupported class file major version 55

java.lang.IllegalArgumentException: Unsupported class file major version 55
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:166)
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:148)
	at io.ebean.enhance.asm.ClassReader.<init>(ClassReader.java:136)
	at io.ebean.eclipse.internal.enhancer.builder.EnhanceBuilder$DetermineClass.getClassName(EnhanceBuilder.java:194)
	at io.ebean.eclipse.internal.enhancer.builder.EnhanceBuilder.process(EnhanceBuilder.java:118)
	at io.ebean.eclipse.internal.enhancer.builder.EnhanceBuilder.checkResource(EnhanceBuilder.java:96)
	at io.ebean.eclipse.internal.enhancer.builder.EnhanceBuilder.access$0(EnhanceBuilder.java:92)
	at io.ebean.eclipse.internal.enhancer.builder.EnhanceBuilder$DeltaVisitor.visit(EnhanceBuilder.java:255)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:67)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:51)
	at io.ebean.eclipse.internal.enhancer.builder.EnhanceBuilder.build(EnhanceBuilder.java:53)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:798)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:219)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:262)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:315)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:318)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:370)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:391)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
`

Ebean eclipse Enhancer plugin  version :  11.11.1.201803270235
Eclipse version : 2018-09 (4.9)
Ebean version : 11.28.3

The ebean-gradle-plugin is working well 

Is it possible to support Java 11 ?

**Comment by rbygrave** [comment]
The Ebean Eclipse plugin hasn't been updated since the ebean-agent was
updated to support java 11 bytecode.

So yes, need to try and do that sometime soon ...

Cheers, Rob.

**Comment by rbygrave** [comment]
Pushed 11.25.1 to https://ebean.io/eclipse/update ... so try that.  Should work for open jdk 11 (although there is a fix in 11.26.1 for the zulu jdk 11)

**Comment by lbernollin** [comment]
@rbygrave  It is working well. Thank you !
